# Generated by Django 3.2.9 on 2021-11-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='website',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='rating',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
